name = "resume-concierge"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[[kv_namespaces]]
binding = "RESUME_KV"
id = "f5abe74ade034ba5a0355bd5b538aaed"

[vars]
ALLOWED_ORIGIN = "https://diegobkc.github.io"
